# Generated by Django 3.1 on 2023-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
