# Generated by Django 4.1.5 on 2023-04-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationmanager_alter_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
